//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets_ex1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Requests = new HashSet<Request>();
            this.Ticket_Action = new HashSet<Ticket_Action>();
            this.Ticket_Log = new HashSet<Ticket_Log>();
        }
    
        public string cod { get; set; }
        public string ticketState { get; set; }
        public string ticketDescription { get; set; }
        public string ticketPriority { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public Nullable<bool> visible { get; set; }
        public Nullable<int> technician { get; set; }
        public string ticketType { get; set; }
        public string ticketUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Request> Requests { get; set; }
        public virtual Technician Technician1 { get; set; }
        public virtual Ticket_Type Ticket_Type { get; set; }
        public virtual Ticket_User Ticket_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Action> Ticket_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket_Log> Ticket_Log { get; set; }
    }
}
