//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets_ex1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vi_Request
    {
        public int orderNumber { get; set; }
        public Nullable<System.DateTime> requestDate { get; set; }
        public Nullable<System.DateTime> responseDate { get; set; }
        public string response { get; set; }
        public string ticket { get; set; }
        public string ticketUser { get; set; }
        public Nullable<int> technician { get; set; }
    }
}
